version: "3"
services:
  reverseproxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: darkphoenix17/udagram-reverse-proxy
  backend_user:
    build:
      context: ../../udagram-backend-user
      dockerfile: Dockerfile
    image: darkphoenix17/udagram-backend-user
  backend_feed:
    build:
      context: ../../udagram-backend-feed
      dockerfile: Dockerfile
    image: darkphoenix17/udagram-backend-feed
  frontend:
    build:
      context: ../../udagram-frontend
      dockerfile: Dockerfile
    image: darkphoenix17/udagram-frontend